### ISSUE TITLE
Comments and typos in Chapter 1

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/book-networks#31]
1. I think it would be nice to label the plots in more detail. i.e. Figure 1.1 on page 3, to have 'exporters' and 'consumers', Figure 1.2 to mention that node size = export value in a caption
2. On page 46, it might be nice to have code that sums the rows and columns for the in/out-degree measures (given that the less efficient version was given above)
3. Page 49, space between 'where c' in the Theorem equation
4. Page 57, space between 'For example, Figure 1.24'

**Comment by rolf-campos** [comment]
5. Page 2, plural/singular in "Figures 1.1 is called a Sankey diagram". 
6. Page 8, superfluous "that" in the sentence "EXERCISE 1.2.6. The trace of a matrix is equal to the sum of its eigenvalues, and that the determinant is their product."

**Comment by rolf-campos** [comment]
7. Page 44, formula for Nash eq. uses notation W instead of A for the adjacency matrix.
8. Page 50, equation 1.32 is not expressed in a way that parallels 1.30 (uses the power -1 instead of a fraction)
9. Page 52, definition of authority-based Katz centrality, maybe add a sentence saying that the i's and j's are flipped relative to eq. 1.34? Or would this make the answer to exercise 1.4.12 too obvious?

**Comment by jstac** [comment]
Many thanks @natashawatkins and @rolf-campos , these comments are greatly appreciated.  I'll address them today.
